Add os check

diff --git a/scripts/brew b/scripts/brew
--- a/scripts/brew
+++ b/scripts/brew
@@ -4,6 +4,11 @@ set -e
 
 cd "$(dirname "$0")/.."
 
+if ! [ "$(uname -s)" = "Darwin" ]; then
+    echo "Error: script only runs on Mac"
+    exit 1
+fi
+
 if ! [ -x "$(command -v brew)" ]; then
     echo "Requires Brew to be installed"
     if [ "$1" == "setup" ]; then
diff --git a/scripts/osx b/scripts/osx
--- a/scripts/osx
+++ b/scripts/osx
@@ -4,8 +4,8 @@ set -e
 
 cd "$(dirname "$0")/.."
 
-if [ "$(uname -s)" = "Darwin" ]; then
-    echo "Error: script only runs on none Mac Unix machines"
+if ! [ "$(uname -s)" = "Darwin" ]; then
+    echo "Error: script only runs on Mac"
     exit 1
 fi
 
